### ISSUE TITLE
multiple src with similar folder structure

### ISSUE THREAD

**Issue by ahmedelgabri** [geut/postcss-copy#43]
So I have a setup like this

```
app/
|__ project/
|    |__assets/
|       |__ imgs/
|       |__ css/
|           |__ app.scss
|    core/
|    |__assets/
|      |__ fonts/ <--- fonts are here
|      |__ imgs/
|
|__ dist/
```

``` js
src: ['app/core/assets', 'app/project/assets'],
dest: 'dist/assets/project',
template: '[path]/[name]-[hash].[ext]',
```

``` css
@font-face {
  font-family: 'font name';
  src: url('../fonts/font-name.woff2') format('woff2');
}
```

It fails to copy the fonts from the directory and it complains that it's not inside the `projectname/assets/fonts` although in the `postcss-copy` config it's one of the `src`.
