### ISSUE TITLE
regression relative url path 

### ISSUE THREAD

**Issue by thisconnect** [geut/postcss-copy#45]
Just updated from 2.6.3 to 5.0.1

something changed that the `url(` used to contain the "dest" path (I believe).
### input

``` css
@import "material-design-icons/iconfont/material-icons.css";
```
### postcss

``` js
postcss([
  importCSS(),
  copyCSS({
      'src': ['node_modules/material-design-icons/iconfont'],
      'dest': 'dist/fonts',
      'template': '[name].[hash].[ext]',
      'keepRelativePath': false
  })
```
### output

``` css

@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(MaterialIcons-Regular.26fb8cecb5512223.eot); /* For IE6-8 */
  src: local('Material Icons'),
       local('MaterialIcons-Regular'),
       url(MaterialIcons-Regular.09963592e8c953cc.woff2) format('woff2'),
       url(MaterialIcons-Regular.c6c953c2ccb2ca9a.woff) format('woff'),
       url(MaterialIcons-Regular.fc05de31234e0090.ttf) format('truetype');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  ...
```
### expected

``` css
url(../fonts/MaterialIcons-Regular.26fb8cecb5512223.eot)
```
