### ISSUE TITLE
handling multiple references to the same source

### ISSUE THREAD

**Issue by thisconnect** [geut/postcss-copy#46]
Hi! :)

I am experimenting with the transform hook and noticed that sometimes the same file is being called. i.e.

real world example (see fontawesome-webfont.eot is referenced twice)

https://github.com/FortAwesome/Font-Awesome/blob/c6e79ae1a1e7bef4e7290e5026b704d24f4fa590/css/font-awesome.css#L9-L10

the same asset could occur in many places

``` css
// buttons.css
.btn-save {
  background-image: url(assets/save.png)
}

// menu.css
.menu-save {
  background: url(assets/save.png) no-repeat
}
```

it seems that 

1) is it correct that postcss-copy only reads the file 1 time?
form the docs

> 1. Read the asset file (using a cache buffer if exists)

2) As far as I see tranform is called for each occurrence/reference in the stylesheet.
therefore using custom optimization (i.e. imagemin) would do duplicated processing

Chaning tranform on a filebase would not be 100% backwards compatible as some people may do different optimization depending on the querystrnig/hash.. altough that might be a rare case.

What would be the best strategy to avoid transforming the same asset multiple times?

3) Would you consider adding a tranformSrc hook that works on filebase?

**Comment by tinchoz49** [comment]
Hi again, 

1) Yes, this is correct, `postcss-copy` only **reads** the file 1 time. We use this to avoid read the file from the src multiple times but the transform is executed in each occurrence of the file.

2) I understand what you are saying about the rare case but I think execute the transform in each occurrence it makes not sense because in the next step (writing the file) if the content doesn't change d we use the content cached so the transform processing was waste of time.

This a bug...the transform process has to be called only when the source is modified.

**Comment by tinchoz49** [comment]
@thisconnect i release a new version with the fix :tada: . Please, can you check if this change solves your problem?

**Comment by thisconnect** [comment]
Thanks! That works for me. I noticed that you pass `query`, `qparams`, `qhash` in fileMeta

If you test 

``` css
span {
    background: url('images/bigimage.jpg?A#A');
}

div {
    background: url('images/bigimage.jpg?B#B');
}
```

It would only report one (the first?) of them.

> Chaning tranform on a filebase would not be 100% backwards compatible as some people may do different optimization depending on the querystrnig/hash.. altough that might be a rare case.

Not sure how this should be handled correctly. But it's no problem for me.
